---
title: "Using existing infrastructure to transform peer review"
date: 2016-02-15
description: "A commentary coauthored with Gary McDowell for the ASAPbio conference on the future of preprints in Biology, arguing for building on existing open access infrastructure rather than starting from scratch."
categories: [Opinions, Publications, Scholarly Communication]
aliases:
  - /2016/02/15/using-existing-infrastructure-to-transform-peer-review/
---

> A commentary I coauthored with Gary McDowell for the forthcoming ASAPbio conference on the future of preprints in Biology. It was originally published at the ASAPbio commentaries section: <a href="http://asapbio.org/open-scholar" target="_blank" rel="noopener noreferrer">http://asapbio.org/open-scholar</a>

In reforming the culture of peer review and moving towards a system that embraces the use and recognition of pre-print servers, we are cognizant of the need to avoid re-inventing the wheel, by identifying and using existing infrastructure and initiatives that can assist in furthering this goal.

<a href="http://www.openscholar.info/">Open Scholar</a> is an open, collectively governed organisation of volunteer researchers that was founded to develop concrete alternatives to the problem of journal-dependent scientific evaluation and communication. We identify the problem of journals and publishers not on whether they offer free or paid access to their content, but on the fact that they all treat knowledge as a material resource that accrues value from exclusivity. However, contrary to material goods, the more knowledge is freely shared, the more value it obtains. It is therefore to the benefit of society and science itself that knowledge, in the form of scientific articles, is made available instantly and in all available means.

Such a way to disseminate articles also enforces a private and local way to evaluate them, which brings a lot of perverse incentives in scientists' collective endeavor. Fortunately, the infrastructure already exists to permit the instant sharing of all research material. Institutional repositories and preprint servers like arXiv, bioRxiv, Zenodo and many more, are now at the reach of every scholar. The problem is the lack of incentive. Why should researchers submit their work to repositories and preprint servers which do not yet offer any recognisable indexes of quality that are essential for grants, hiring and promotion?

Today we run two parallel projects whose aim is to disentangle the process of research evaluation from publication in academic journals and to offer incentives for a community-driven scholarly communication system. The first was developed with the support of OpenAIRE, to provide an evaluation system to be offered by existing repositories as an overlay service [see: <a href="http://www.openscholar.info/wp-content/uploads/2015/08/OPRM_OpenAIRE_Tender.pdf">OPRM: An Open Peer Review Module for integration with OA repositories</a>]. For this project, in collaboration with two experienced artificial intelligence research groups, we have developed sophisticated reputation algorithms for articles, authors, reviews and reviewers. The second, so far developed by our own means without any financial support, is a free, multidisciplinary repository called the Self-Journal of Science (SJS; <a href="http://www.sjscience.org/">www.sjscience.org</a>). SJS comes with an innovative peer review system already integrated. Peer review at SJS is implemented as an open and transparent community debate aiming to accumulate expert, substantiated opinions on whether a given research work has reached acceptable scientific standards or still needs revisions. Contrary to the closed, anonymous and time-limited "peer trials" employed by most journals, SJS peer review is not concerned about the possible importance of an article. Importance at SJS is assessed as a different and unrelated parameter by means of inclusion in self-journals, which are collections of articles around a specific topic curated by individual researchers. In their self-journals, curators can include articles hosted in other repositories or published by traditional publishers. There are a number of arguments why this novel means of personal communication has incentives and provides a thorough basis for a proper assessment of the importance of any one article. In addition, SJS offers a dynamic research classification system based on a tag hierarchical structure that evolves dynamically and consensually to better fit the needs of rapidly developing disciplines. Strategically, the most important feature of SJS is that it generates unique, thorough and simple community-based metrics that incentivize openness, transparency, reproducibility and fruitful interaction between peers. As a result, it incentivizes a convergent interest, for maximal scientific quality. We argue that adoption of these easy-to-use metrics by institutions and funding agencies would eventually transform the publishing process in a self-correcting and costless way.

## Call to action

Our call to action is very concrete. As most of the commentaries in this section also suggest, it seems that the change we are all waiting for will eventually be brought by repositories and preprint servers. Our suggestion to the community is to build on top of what we already have, instead of starting from scratch. We have done everything possible within our financial limitations and lack of resources to create an organisation that fellow researchers can trust. Open Scholar is a non-profit, community interest company (<a href="http://www.openscholar.info/an-open-organisation/">http://www.openscholar.info/an-open-organisation/</a>) whose assets cannot ever be transferred to a for-profit. Membership is free and open to the academic community. Any member can participate as a volunteer in the working team, which has an horizontal structure and is responsible for everyday decisions. More important decisions are made after consulting all the members of the organisation via email or in general meetings held at least once a year.

We invite you to visit SJS to get a first hand experience of the evaluation and classification services it offers. Then come and join us, make Open Scholar projects your own and contribute to their improvement and promotion. If you don't like what you see and do not wish to share your ideas for improvements, you can always try to develop your own platform, repository or preprint server. We believe, however, that the most efficient approach is to join forces and merge existing initiatives instead of further dispersing our creativity and resources to create yet another competitive market of "alternative" publishing channels. Only an open collaboration motivated by a genuine interest to protect Science from the interests of commercial enterprises and the self-righteousness of closed academic groups can bring real change.
